name: CI
on: [pull_request]
jobs:
  test:
    runs-on: macos-15-arm64
    steps:
      - uses: actions/checkout@v4
      - run: sw_vers
      - run: uname -a
      - run: swift --version
      - run: xcrun --version
      - run: xcodebuild -version
      - run: xcodebuild -version -sdk
      - run: xcode-select -h