name: CI

on: pull_request

jobs:
  public-api-diff:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: zunda-pixel/adyen-swift-public-api-diff@fix-output
        id: generate-diff
        with:
          platform: "iOS"
          new: "test-publi-api-diff~https://github.com/Adyen/adyen-ios.git"
          old: "main~https://github.com/Adyen/adyen-ios.git"
      - run: echo  "${{ steps.generate-diff.outputs.message }}"
